# Generated by Django 4.0.6 on 2022-07-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0002_rename_price_product_unit_price_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
