# Generated by Django 4.0.6 on 2022-07-19 20:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0004_alter_collection_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
